/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to implement dynamic world coordinate extraction for the monitor screen!
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState, useMemo } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { motion, AnimatePresence } from 'framer-motion'


function PostSequence({ onComplete }: { onComplete: () => void }) {
  const ramRef = useRef<HTMLSpanElement>(null);
  const [step, setStep] = useState(0);

  useEffect(() => {
    if (step === 1) {
      const timer = setTimeout(() => {
        onComplete();
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [step, onComplete]);

  useEffect(() => {
    let raf: number;
    const startTime = Date.now() + 500;
    const ramDuration = 1500;

    const animateRam = () => {
      const now = Date.now();
      if (now < startTime) {
        raf = requestAnimationFrame(animateRam);
        return;
      }
      const progress = Math.min((now - startTime) / ramDuration, 1);
      if (ramRef.current) {
        ramRef.current.textContent = `${Math.floor(progress * 640)}K OK`;
      }
      if (progress < 1) {
        raf = requestAnimationFrame(animateRam);
      } else {
        setStep(1); // RAM done, show drivers
      }
    };
    raf = requestAnimationFrame(animateRam);
    return () => cancelAnimationFrame(raf);
  }, []);

  return (
    <div className="w-full h-full bg-black text-white font-mono text-sm p-4 text-left">
      <div className="flex justify-between w-full max-w-sm">
        <span>American Megatrends Inc.</span>
        <span>640K RAM SYSTEM</span>
      </div>
      <p>System BIOS (C) 1995</p>
      <p>HHBIOS (C) 2026 Lozada</p>
      <br />
      <div className="flex gap-4 text-green-400">
        <span>Checking Memory...</span>
        <span ref={ramRef}>0K OK</span>
      </div>
      {step >= 1 && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mt-4 space-y-1 text-gray-300">
          <p>Loading Mouse Driver... OK</p>
          <p>Loading SoundBlaster 16... OK</p>
          <p>Loading Video Adapter... VESA BIOS Extension 3.0</p>
          <p>Mounting Virtual File System (VFS)... OK</p>
          <br />
          <p className="animate-pulse">_</p>
        </motion.div>
      )}
    </div>
  );
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_21: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_23: THREE.Mesh
  }
  materials: {
    computer_details: THREE.MeshStandardMaterial
    computer_keyboard: THREE.MeshStandardMaterial
    computer_main_body: THREE.MeshStandardMaterial
    peripherals: THREE.MeshStandardMaterial
    cable: THREE.MeshStandardMaterial
    connector: THREE.MeshStandardMaterial
    monitor_white: THREE.MeshStandardMaterial
    monitor_black: THREE.MeshStandardMaterial
    monitor_screen: THREE.MeshPhysicalMaterial
    monitor_plug: THREE.MeshStandardMaterial
  }
}

export function Commodore64(props: React.JSX.IntrinsicElements['group'] & { 
  bootPhase?: 'off' | 'post' | 'video' | 'os';
  setBootPhase?: (phase: 'off' | 'post' | 'video' | 'os') => void;
  onAutoAlign?: (pos: [number, number, number]) => void;
  scaleFactor?: number;
  positionOffset?: [number, number, number];
  onMonitorEnter3D?: () => void;
  onMonitorLeave3D?: () => void;
  onMonitorDown3D?: () => void;
  onMonitorUp3D?: () => void;
  onMonitorEnterHTML?: () => void;
  onMonitorLeaveHTML?: () => void;
  isShuttingDown?: boolean;
  isSafeToTurnOff?: boolean;
  powerDownComplete?: boolean;
  showShutdownDialog?: boolean;
  onConfirmShutdown?: () => void;
  onCancelShutdown?: () => void;
  onShutdownComplete?: () => void;
}) {
  const { nodes, materials } = useGLTF('/commodore_64__computer_full_pack.glb') as unknown as GLTFResult
  
  const screenRef = useRef<THREE.Mesh>(null);
  const [targetReady, setTargetReady] = useState(false);

  const [screenPos, setScreenPos] = useState<THREE.Vector3 | null>(null);

  useEffect(() => {
    if (!nodes.Object_19.geometry.boundingBox) {
      nodes.Object_19.geometry.computeBoundingBox();
    }
    const center = new THREE.Vector3();
    nodes.Object_19.geometry.boundingBox?.getCenter(center);
    
    // The screen curves outward. The center Z is inside the glass.
    // The very front tip of the glass is the bounding box max Z.
    const maxZ = nodes.Object_19.geometry.boundingBox?.max.z || center.z;
    
    setScreenPos(new THREE.Vector3(center.x, center.y, maxZ + 0.01)); // Place exactly on the glass surface
  }, [nodes.Object_19.geometry]);

  useEffect(() => {
    if (screenRef.current && screenPos && props.onAutoAlign) {
      screenRef.current.updateMatrixWorld(true);
      const worldCenter = screenPos.clone().applyMatrix4(screenRef.current.matrixWorld);
      props.onAutoAlign([worldCenter.x, worldCenter.y, worldCenter.z]);
      setTargetReady(true);
    }
  }, [screenPos, props.onAutoAlign]);

  return (
    <group {...props} dispose={null}>
      <group position={[-1.258, 0.195, 2.2]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.computer_details} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.computer_keyboard} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.computer_main_body} />
      </group>
      <group position={[0.542, -0.111, -4.23]}>
        <mesh geometry={nodes.Object_14.geometry} material={materials.cable} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.connector} />
      </group>
      
      <group 
        position={[0, 0.368, -2.43]}
        onPointerEnter={props.onMonitorEnter3D}
        onPointerOut={props.onMonitorLeave3D}
      >
        <mesh geometry={nodes.Object_17.geometry} material={materials.monitor_black} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.monitor_white} />
        
        {/* The distinct, separate screen mesh! */}
        <mesh 
          ref={screenRef} 
          geometry={nodes.Object_19.geometry} 
          material={materials.monitor_screen}
          onPointerDown={props.onMonitorDown3D}
          onPointerUp={props.onMonitorUp3D}
        >
          {screenPos && (
            <Html 
              transform 
              occlude="blending"
              position={[
                screenPos.x + (props.positionOffset?.[0] || 0), 
                screenPos.y + (props.positionOffset?.[1] || 0), 
                screenPos.z + 0.005 + (props.positionOffset?.[2] || 0) // Extra Z-offset to prevent z-fighting
              ]}
              scale={props.scaleFactor || 0.114} // Recalibrated for 1024px width (0.146 * 800 / 1024)
              className="w-[1024px] h-[768px] bg-black flex items-center justify-center border-[8px] border-[#0a0a0a]"
              style={{ borderRadius: '64px', overflow: 'hidden' }}
            >
              <div 
                className="w-full h-full relative p-5 bg-black" 
                style={{ borderRadius: '64px', overflow: 'hidden' }}
                onMouseEnter={props.onMonitorEnterHTML}
                onMouseLeave={props.onMonitorLeaveHTML}
                onPointerDown={props.onMonitorDown3D}
                onPointerUp={props.onMonitorUp3D}
              >
                {/* Screen Content Wrapper with CSS Safe Zone (inset-[24px]) */}
                <div className="absolute inset-[24px] bg-black z-0 flex items-center justify-center overflow-hidden rounded-lg">
                  <AnimatePresence>
                    {props.bootPhase !== 'off' && (
                      <motion.div
                        key="boot"
                        initial={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.5 }}
                        className="w-full h-full absolute inset-0 bg-black"
                      >
                        {props.bootPhase === 'post' && !props.isShuttingDown && <PostSequence onComplete={() => props.setBootPhase?.('video')} />}
                        {(props.bootPhase === 'post' || props.bootPhase === 'video') && !props.isShuttingDown && (
                          <video 
                            ref={(el) => {
                              if (el && props.bootPhase === 'video') {
                                el.play().catch(console.error);
                              }
                            }}
                            src="/video/startup.mp4?v=2" 
                            className="w-full h-full object-cover absolute inset-0 z-40 pointer-events-none"
                            style={{ opacity: props.bootPhase === 'video' ? 1 : 0 }}
                            playsInline 
                            preload="auto"
                            onEnded={() => props.setBootPhase?.('os')}
                          />
                        )}
                        {props.bootPhase === 'os' && !props.isShuttingDown && (
                          <iframe 
                            src="/monitor-os/index.html" 
                            className="w-full h-full border-0 pointer-events-auto"
                            title="Desktop OS"
                          />
                        )}

                        {/* Always mount shutdown video so it preloads fully and plays instantly */}
                        <video 
                          ref={(el) => {
                            if (el && props.isShuttingDown) {
                              el.play().catch(console.error);
                            }
                          }}
                          src="/video/shutdown.mp4?v=2" 
                          className="w-full h-full object-cover absolute inset-0 z-50 pointer-events-none"
                          style={{ opacity: props.isShuttingDown ? 1 : 0 }}
                          playsInline 
                          preload="auto"
                          onEnded={() => props.onShutdownComplete?.()}
                        />
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>    {/* Render the Windows 95 Dialog INSIDE the 3D Monitor! */}
                  <AnimatePresence>
                    {props.showShutdownDialog && (
                      <motion.div 
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 0.95 }}
                        className="absolute inset-0 z-[50] flex items-center justify-center pointer-events-auto bg-black/20 backdrop-blur-[1px]"
                      >
                        {/* Windows 95 Dialog Box */}
                        <div className="bg-[#c0c0c0] p-[2px] border-t-2 border-l-2 border-t-[#dfdfdf] border-l-[#dfdfdf] border-b-2 border-r-2 border-b-black border-r-black shadow-md font-sans text-black antialiased w-[400px]">
                          {/* Title Bar */}
                          <div className="bg-[#000080] text-white font-bold px-1 py-0.5 flex justify-between items-center text-sm" style={{ WebkitFontSmoothing: 'none' }}>
                            <span>Shut Down Windows</span>
                            <button onClick={props.onCancelShutdown} className="bg-[#c0c0c0] text-black font-bold px-1.5 border-t border-l border-t-white border-l-white border-b border-r border-b-black border-r-black text-xs leading-none pb-0.5 active:border-t-black active:border-l-black active:border-b-white active:border-r-white">X</button>
                          </div>
                          {/* Content */}
                          <div className="p-4 text-[13px] flex" style={{ WebkitFontSmoothing: 'none', fontFamily: "'Pixelated MS Sans Serif', 'MS Sans Serif', Tahoma, sans-serif" }}>
                            <div className="mr-4 mt-2">
                              {/* Classic computer icon placeholder */}
                              <img src="https://win98icons.alexmeub.com/icons/png/computer_explorer-4.png" alt="Computer" className="w-8 h-8 pixelated" />
                            </div>
                            <div className="flex-1">
                              <p className="mb-4">Are you sure you want to:</p>
                              
                              <div className="flex flex-col gap-2 mb-6">
                                <label className="flex items-center gap-2 cursor-pointer group">
                                  <div className="w-3 h-3 rounded-full border border-black bg-white flex items-center justify-center group-has-[:checked]:ring-2 group-has-[:checked]:ring-[#c0c0c0] group-has-[:checked]:ring-inset">
                                    <div className="w-1.5 h-1.5 bg-black rounded-full hidden group-has-[:checked]:block" />
                                  </div>
                                  <input type="radio" name="shutdown" defaultChecked className="sr-only" />
                                  <span>Shut down the computer?</span>
                                </label>
                                <label className="flex items-center gap-2 cursor-pointer group">
                                  <div className="w-3 h-3 rounded-full border border-black bg-white flex items-center justify-center group-has-[:checked]:ring-2 group-has-[:checked]:ring-[#c0c0c0] group-has-[:checked]:ring-inset">
                                    <div className="w-1.5 h-1.5 bg-black rounded-full hidden group-has-[:checked]:block" />
                                  </div>
                                  <input type="radio" name="shutdown" className="sr-only" />
                                  <span>Restart the computer?</span>
                                </label>
                                <label className="flex items-center gap-2 cursor-pointer group">
                                  <div className="w-3 h-3 rounded-full border border-black bg-white flex items-center justify-center group-has-[:checked]:ring-2 group-has-[:checked]:ring-[#c0c0c0] group-has-[:checked]:ring-inset">
                                    <div className="w-1.5 h-1.5 bg-black rounded-full hidden group-has-[:checked]:block" />
                                  </div>
                                  <input type="radio" name="shutdown" className="sr-only" />
                                  <span>Restart the computer in MS-DOS mode?</span>
                                </label>
                                <label className="flex items-center gap-2 cursor-pointer group">
                                  <div className="w-3 h-3 rounded-full border border-black bg-white flex items-center justify-center group-has-[:checked]:ring-2 group-has-[:checked]:ring-[#c0c0c0] group-has-[:checked]:ring-inset">
                                    <div className="w-1.5 h-1.5 bg-black rounded-full hidden group-has-[:checked]:block" />
                                  </div>
                                  <input type="radio" name="shutdown" className="sr-only" />
                                  <span>Close all programs and log on as a different user?</span>
                                </label>
                              </div>

                              <div className="flex gap-2 justify-end mt-4">
                                <button onClick={props.onConfirmShutdown} className="px-5 py-1 bg-[#c0c0c0] border-t-2 border-l-2 border-t-white border-l-white border-b-2 border-r-2 border-b-black border-r-black active:border-t-black active:border-l-black active:border-b-white active:border-r-white focus:outline-dotted focus:outline-1 focus:outline-offset-[-4px]">Yes</button>
                                <button onClick={props.onCancelShutdown} className="px-5 py-1 bg-[#c0c0c0] border-t-2 border-l-2 border-t-white border-l-white border-b-2 border-r-2 border-b-black border-r-black active:border-t-black active:border-l-black active:border-b-white active:border-r-white focus:outline-dotted focus:outline-1 focus:outline-offset-[-4px]">No</button>
                                <button className="px-5 py-1 bg-[#c0c0c0] border-t-2 border-l-2 border-t-white border-l-white border-b-2 border-r-2 border-b-black border-r-black active:border-t-black active:border-l-black active:border-b-white active:border-r-white focus:outline-dotted focus:outline-1 focus:outline-offset-[-4px]">Help</button>
                              </div>
                            </div>
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>



                  {/* Scanline Overlay (always on top) */}
                <div className="absolute inset-0 pointer-events-none z-[200] mix-blend-overlay opacity-30" 
                  style={{
                    backgroundImage: "linear-gradient(transparent 50%, rgba(0, 0, 0, 0.5) 50%)",
                    backgroundSize: "100% 4px"
                  }}
                />
                <div className="absolute inset-0 pointer-events-none z-[200] mix-blend-screen opacity-10 bg-gradient-to-tr from-transparent via-white to-transparent" />
              </div>
            </Html>
          )}
        </mesh>

        <mesh geometry={nodes.Object_21.geometry} material={materials.monitor_white} position={[1.265, -0.148, 2.24]} rotation={[Math.PI / 2, 0, 0]} />
      </group>

      <mesh geometry={nodes.Object_8.geometry} material={materials.peripherals} position={[3.182, 0.071, -2.601]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.peripherals} position={[4.297, 0.478, 1.302]} rotation={[0, 0.602, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.peripherals} position={[-4.423, 1.212, -1.111]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.monitor_plug} position={[0.003, 2.252, -2.083]} />
    </group>
  )
}

useGLTF.preload('/commodore_64__computer_full_pack.glb')
