/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to implement dynamic world coordinate extraction for the monitor screen!
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState, useMemo } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { motion, AnimatePresence } from 'framer-motion'
import { OSBootSequence } from './hero-section'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_21: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_23: THREE.Mesh
  }
  materials: {
    computer_details: THREE.MeshStandardMaterial
    computer_keyboard: THREE.MeshStandardMaterial
    computer_main_body: THREE.MeshStandardMaterial
    peripherals: THREE.MeshStandardMaterial
    cable: THREE.MeshStandardMaterial
    connector: THREE.MeshStandardMaterial
    monitor_white: THREE.MeshStandardMaterial
    monitor_black: THREE.MeshStandardMaterial
    monitor_screen: THREE.MeshPhysicalMaterial
    monitor_plug: THREE.MeshStandardMaterial
  }
}

export function Commodore64(props: React.JSX.IntrinsicElements['group'] & { 
  isBootingOS?: boolean;
  isAwaitingBoot?: boolean;
  onCompleteBoot?: () => void;
  onAutoAlign?: (pos: [number, number, number]) => void;
  scaleFactor?: number;
  positionOffset?: [number, number, number];
  onMonitorEnter3D?: () => void;
  onMonitorLeave3D?: () => void;
  onMonitorDown3D?: () => void;
  onMonitorUp3D?: () => void;
  onMonitorEnterHTML?: () => void;
  onMonitorLeaveHTML?: () => void;
  isShuttingDown?: boolean;
  isSafeToTurnOff?: boolean;
  powerDownComplete?: boolean;
}) {
  const { nodes, materials } = useGLTF('/commodore_64__computer_full_pack.glb') as unknown as GLTFResult
  
  const screenRef = useRef<THREE.Mesh>(null);
  const [targetReady, setTargetReady] = useState(false);

  const [screenPos, setScreenPos] = useState<THREE.Vector3 | null>(null);

  useEffect(() => {
    if (!nodes.Object_19.geometry.boundingBox) {
      nodes.Object_19.geometry.computeBoundingBox();
    }
    const center = new THREE.Vector3();
    nodes.Object_19.geometry.boundingBox?.getCenter(center);
    
    // The screen curves outward. The center Z is inside the glass.
    // The very front tip of the glass is the bounding box max Z.
    const maxZ = nodes.Object_19.geometry.boundingBox?.max.z || center.z;
    
    setScreenPos(new THREE.Vector3(center.x, center.y, maxZ + 0.01)); // Place exactly on the glass surface
  }, [nodes.Object_19.geometry]);

  useEffect(() => {
    if (screenRef.current && screenPos && props.onAutoAlign) {
      screenRef.current.updateMatrixWorld(true);
      const worldCenter = screenPos.clone().applyMatrix4(screenRef.current.matrixWorld);
      props.onAutoAlign([worldCenter.x, worldCenter.y, worldCenter.z]);
      setTargetReady(true);
    }
  }, [screenPos, props.onAutoAlign]);

  return (
    <group {...props} dispose={null}>
      <group position={[-1.258, 0.195, 2.2]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.computer_details} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.computer_keyboard} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.computer_main_body} />
      </group>
      <group position={[0.542, -0.111, -4.23]}>
        <mesh geometry={nodes.Object_14.geometry} material={materials.cable} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.connector} />
      </group>
      
      <group 
        position={[0, 0.368, -2.43]}
        onPointerEnter={props.onMonitorEnter3D}
        onPointerOut={props.onMonitorLeave3D}
      >
        <mesh geometry={nodes.Object_17.geometry} material={materials.monitor_black} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.monitor_white} />
        
        {/* The distinct, separate screen mesh! */}
        <mesh 
          ref={screenRef} 
          geometry={nodes.Object_19.geometry} 
          material={materials.monitor_screen}
          onPointerDown={props.onMonitorDown3D}
          onPointerUp={props.onMonitorUp3D}
        >
          {screenPos && (
            <Html 
              transform 
              occlude="blending"
              position={[
                screenPos.x + (props.positionOffset?.[0] || 0), 
                screenPos.y + (props.positionOffset?.[1] || 0), 
                screenPos.z + 0.005 + (props.positionOffset?.[2] || 0) // Extra Z-offset to prevent z-fighting
              ]}
              scale={props.scaleFactor || 0.114} // Recalibrated for 1024px width (0.146 * 800 / 1024)
              className="w-[1024px] h-[768px] bg-black flex items-center justify-center border-[8px] border-[#0a0a0a]"
              style={{ borderRadius: '64px', overflow: 'hidden' }}
            >
              <div 
                className="w-full h-full relative p-5 bg-black" 
                style={{ borderRadius: '64px', overflow: 'hidden' }}
                onMouseEnter={props.onMonitorEnterHTML}
                onMouseLeave={props.onMonitorLeaveHTML}
              >
                {/* CRT Power Down Animation Wrapper with CSS Safe Zone (inset-6) */}
                <motion.div 
                  className="absolute inset-[24px] bg-black z-0 flex items-center justify-center overflow-hidden rounded-lg"
                  animate={props.powerDownComplete ? {
                    scaleY: [1, 0.01, 0.01, 0],
                    scaleX: [1, 1, 0.01, 0],
                    opacity: [1, 1, 0.8, 0],
                    backgroundColor: ["#000", "#fff", "#fff", "#000"]
                  } : {}}
                  transition={{ 
                    duration: 0.8, 
                    times: [0, 0.3, 0.6, 1],
                    ease: "easeIn" 
                  }}
                  style={{ transformOrigin: 'center center' }}
                >
                  <AnimatePresence>
                    {!props.isShuttingDown && !props.isAwaitingBoot && (
                      <motion.div
                        initial={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.5 }}
                        className="w-full h-full absolute inset-0"
                      >
                        {props.isBootingOS ? (
                          <OSBootSequence onComplete={() => props.onCompleteBoot?.()} />
                        ) : (
                          <iframe 
                            src="/monitor-os/index.html" 
                            className="w-full h-full border-0 pointer-events-auto"
                            title="Desktop OS"
                          />
                        )}
                      </motion.div>
                    )}
                  </AnimatePresence>

                  <AnimatePresence>
                    {props.isSafeToTurnOff && (
                      <motion.div 
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        className="absolute inset-0 z-[100] flex items-center justify-center bg-black"
                      >
                        <p className="text-[#FF8C00] font-sans text-2xl max-w-md text-center leading-relaxed" style={{ textShadow: "1px 1px 0px #000, -1px -1px 0px #000, 1px -1px 0px #000, -1px 1px 0px #000" }}>
                          It is now safe to turn off your computer.
                        </p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>

                {/* Scanline Overlay (always on top) */}
                <div className="absolute inset-0 pointer-events-none z-[200] mix-blend-overlay opacity-30" 
                  style={{
                    backgroundImage: "linear-gradient(transparent 50%, rgba(0, 0, 0, 0.5) 50%)",
                    backgroundSize: "100% 4px"
                  }}
                />
                <div className="absolute inset-0 pointer-events-none z-[200] mix-blend-screen opacity-10 bg-gradient-to-tr from-transparent via-white to-transparent" />
              </div>
            </Html>
          )}
        </mesh>

        <mesh geometry={nodes.Object_21.geometry} material={materials.monitor_white} position={[1.265, -0.148, 2.24]} rotation={[Math.PI / 2, 0, 0]} />
      </group>

      <mesh geometry={nodes.Object_8.geometry} material={materials.peripherals} position={[3.182, 0.071, -2.601]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.peripherals} position={[4.297, 0.478, 1.302]} rotation={[0, 0.602, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.peripherals} position={[-4.423, 1.212, -1.111]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.monitor_plug} position={[0.003, 2.252, -2.083]} />
    </group>
  )
}

useGLTF.preload('/commodore_64__computer_full_pack.glb')
