/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\decor.glb -o src\components\public\decor.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    binder_1: THREE.Mesh
    coffee: THREE.Mesh
    paper: THREE.Mesh
    paper_holder_bottom: THREE.Mesh
    paper_stack_1: THREE.Mesh
    paper_stack_2: THREE.Mesh
    plant: THREE.Mesh
    paper_holder_top: THREE.Mesh
    binder_2: THREE.Mesh
  }
  materials: Record<string, unknown>
  animations: unknown[]
}

export function DecorModel(props: React.JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/decor.glb') as unknown as GLTFResult
  const bakedTexture = useTexture('/baked_decor_modified.jpg')
  bakedTexture.flipY = false
  bakedTexture.colorSpace = THREE.SRGBColorSpace

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.binder_1.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.coffee.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.paper.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.paper_holder_bottom.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.paper_stack_1.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.paper_stack_2.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.plant.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.paper_holder_top.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.binder_2.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/decor.glb')
