/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\environment.glb -o src\components\public\environment.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Background: THREE.Mesh
    desk: THREE.Mesh
    chair_base: THREE.Mesh
    chair_seat: THREE.Mesh
  }
  materials: Record<string, unknown>
  animations: unknown[]
}

export function EnvironmentModel(props: React.JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/environment.glb') as unknown as GLTFResult
  const bakedTexture = useTexture('/baked_environment.jpg')
  bakedTexture.flipY = false
  bakedTexture.colorSpace = THREE.SRGBColorSpace

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Background.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.desk.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.chair_base.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.chair_seat.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/environment.glb')
