/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\ibm-pcjr-4863-computer-freepolyorg_2.glb -o src\components\public\ibm-pc.tsx 
Author: Bricksant15 (https://sketchfab.com/Bricksant15)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ibm-pcjr-4863-computer-freepolyorg-2-071b50cfb615440bb952a21197da56d7
Title: ibm-pcjr-4863-computer-freepolyorg 2
*/

import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
    defaultMaterial_4: THREE.Mesh
    defaultMaterial_5: THREE.Mesh
    defaultMaterial_6: THREE.Mesh
  }
  materials: {
    default_1001: THREE.MeshStandardMaterial
    default_1005: THREE.MeshStandardMaterial
    default_1002: THREE.MeshStandardMaterial
    default_1004: THREE.MeshStandardMaterial
    default_1003: THREE.MeshStandardMaterial
    default_1006: THREE.MeshStandardMaterial
    default_1007: THREE.MeshStandardMaterial
  }
  animations: unknown[]
}

import { OSBootSequence } from './hero-section' // Assuming OSBootSequence can be exported from hero-section.tsx

export function Model(props: React.JSX.IntrinsicElements['group'] & { isBootingOS?: boolean, onCompleteBoot?: () => void }) {
  const { nodes, materials } = useGLTF('/ibm-pcjr-4863-computer-freepolyorg_2.glb') as unknown as GLTFResult

  // Calibration state for the Html wrapper
  const [config, setConfig] = useState({ x: 0, y: 140, z: 120, rx: 0, ry: 0, rz: 0, scale: 0.1 });
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.default_1001} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.default_1005} />
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.default_1002} />
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.default_1004} />
            <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.default_1003} />
            <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.default_1006} />
            <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.default_1007} />
          </group>
        </group>
      </group>

      {/* Embedded OS Screen */}
      <Html 
        transform 
        occlude="blending"
        position={[config.x, config.y, config.z]} 
        rotation={[config.rx, config.ry, config.rz]}
        scale={config.scale}
        className="w-[800px] h-[600px] bg-black overflow-hidden flex items-center justify-center border-4 border-black/50"
      >
        <div className="w-full h-full relative" style={{ borderRadius: '24px', overflow: 'hidden' }}>
          <div className="absolute inset-0 pointer-events-none z-50 mix-blend-overlay opacity-30" 
            style={{
              backgroundImage: "linear-gradient(transparent 50%, rgba(0, 0, 0, 0.5) 50%)",
              backgroundSize: "100% 4px"
            }}
          />
          <div className="absolute inset-0 pointer-events-none z-50 mix-blend-screen opacity-10 bg-gradient-to-tr from-transparent via-white to-transparent" />
          
          {props.isBootingOS ? (
            <OSBootSequence onComplete={() => props.onCompleteBoot?.()} />
          ) : (
            <iframe 
              src="/monitor-os/index.html" 
              className="w-full h-full border-0"
              title="Desktop OS"
            ></iframe>
          )}
        </div>
      </Html>
    </group>
  )
}

useGLTF.preload('/ibm-pcjr-4863-computer-freepolyorg_2.glb')
