/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to include the embedded OS screen with fully AUTOMATED Raycast alignment.
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { OSBootSequence } from './hero-section'

type GLTFResult = GLTF & {
  nodes: {
    old_pc000_Room_mat_0_0: THREE.Mesh
    old_pc000_Room_mat_0_1: THREE.Mesh
  }
  materials: {
    Room_mat: THREE.MeshStandardMaterial
  }
  animations: unknown[]
}

export function SadOfficeRoom(props: React.JSX.IntrinsicElements['group'] & { 
  isBootingOS?: boolean;
  onCompleteBoot?: () => void;
  onAutoAlign?: (pos: [number, number, number]) => void;
}) {
  const { nodes, materials } = useGLTF('/Sad_Office_Room/Sad_Office_Room.glb') as unknown as GLTFResult
  
  const roomGroupRef = useRef<THREE.Group>(null);
  
  // State for the programmatically calculated coordinates
  const [autoConfig, setAutoConfig] = useState<{
    pos: [number, number, number],
    rot: [number, number, number],
    ready: boolean
  }>({
    pos: [0, 0, 0],
    rot: [0, 0, 0],
    ready: false
  });

  // Automated Initialization Script: Finds the monitor screen surface programmatically
  useEffect(() => {
    if (!roomGroupRef.current) return;

    // We know the user was looking from [0, 0, 15] towards [6.237, 1.437, -31.029] during the visual test.
    // This perfectly defines a 3D ray that passes straight through the center of the monitor glass.
    const origin = new THREE.Vector3(0, 0, 15);
    const target = new THREE.Vector3(6.237, 1.437, -31.029);
    const direction = new THREE.Vector3().subVectors(target, origin).normalize();

    const raycaster = new THREE.Raycaster(origin, direction);
    
    // Ensure the matrices are updated so world coordinates are accurate
    roomGroupRef.current.updateMatrixWorld(true);

    // Intersect against the monolithic room mesh
    const intersects = raycaster.intersectObject(roomGroupRef.current, true);

    if (intersects.length > 0) {
      // The first hit is guaranteed to be the CRT monitor screen surface!
      const hit = intersects[0];
      
      // 1. Get exact world position (offset slightly outward by 1mm to prevent Z-fighting occlusion)
      const worldNormal = hit.face?.normal.clone().transformDirection(hit.object.matrixWorld).normalize() || new THREE.Vector3(0, 0, 1);
      const exactPos = hit.point.clone().add(worldNormal.clone().multiplyScalar(0.001));

      // 2. Calculate exact rotation to sit perfectly flush against the glass
      // A plane faces +Z by default, so we align +Z to the surface normal
      const quaternion = new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 0, 1), worldNormal);
      const euler = new THREE.Euler().setFromQuaternion(quaternion);

      // 3. Auto-apply to the HTML overlay
      setAutoConfig({
        pos: [exactPos.x, exactPos.y, exactPos.z],
        rot: [euler.x, euler.y, euler.z],
        ready: true
      });
      
      if (props.onAutoAlign) {
        props.onAutoAlign([exactPos.x, exactPos.y, exactPos.z]);
      }
      
      console.log("Programmatic Alignment Success:", { pos: exactPos, rot: euler });
    }
  }, []);

  return (
    <group {...props} dispose={null}>
      {/* Target monolithic group for the automated Raycaster */}
      <group ref={roomGroupRef} position={[0.299, -5.067, -23.901]} rotation={[-1.476, 0, -1.024]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.495, 4.612, -4.267]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.old_pc000_Room_mat_0_0.geometry} material={materials.Room_mat} />
            <mesh geometry={nodes.old_pc000_Room_mat_0_1.geometry} material={materials.Room_mat} />
          </group>
        </group>
      </group>

      {/* Embedded OS Screen - Dynamically snapped via automated Raycast logic */}
      {autoConfig.ready && (
        <Html 
          transform 
          occlude="blending"
          position={autoConfig.pos} 
          rotation={autoConfig.rot}
          scale={0.286}
          className="w-[800px] h-[600px] bg-black flex items-center justify-center border-4 border-[#0a0a0a]"
          style={{ borderRadius: '32px', overflow: 'hidden' }}
        >
          <div className="w-full h-full relative" style={{ borderRadius: '32px', overflow: 'hidden' }}>
            <div className="absolute inset-0 pointer-events-none z-50 mix-blend-overlay opacity-30" 
              style={{
                backgroundImage: "linear-gradient(transparent 50%, rgba(0, 0, 0, 0.5) 50%)",
                backgroundSize: "100% 4px"
              }}
            />
            <div className="absolute inset-0 pointer-events-none z-50 mix-blend-screen opacity-10 bg-gradient-to-tr from-transparent via-white to-transparent" />
            
            {props.isBootingOS ? (
              <OSBootSequence onComplete={() => props.onCompleteBoot?.()} />
            ) : (
              <iframe 
                src="/monitor-os/index.html" 
                className="w-full h-full border-0"
                title="Desktop OS"
              ></iframe>
            )}
          </div>
        </Html>
      )}
    </group>
  )
}

useGLTF.preload('/Sad_Office_Room/Sad_Office_Room.glb')
