/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to include calibration screen plane with TransformControls.
*/

import * as THREE from 'three'
import React, { useRef, useEffect } from 'react'
import { useGLTF, TransformControls } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    old_pc000_Room_mat_0_0: THREE.Mesh
    old_pc000_Room_mat_0_1: THREE.Mesh
  }
  materials: {
    Room_mat: THREE.MeshStandardMaterial
  }
  animations: unknown[]
}

type ScreenConfig = { x: number; y: number; z: number; rx: number; ry: number; rz: number; scale: number };

export function SadOfficeRoom(props: React.JSX.IntrinsicElements['group'] & { 
  screenConfig?: ScreenConfig;
  transformMode?: 'translate' | 'rotate' | 'scale';
  onTransformChange?: (config: ScreenConfig) => void;
}) {
  const { nodes, materials } = useGLTF('/Sad_Office_Room/Sad_Office_Room.glb') as unknown as GLTFResult
  
  const meshRef = useRef<THREE.Mesh>(null);
  const config = props.screenConfig ?? { x: 0, y: 0, z: 0, rx: 0, ry: 0, rz: 0, scale: 1 };

  // Sync incoming config to the mesh, but only if it's not currently being dragged by TransformControls
  const isDragging = useRef(false);
  useEffect(() => {
    if (meshRef.current && !isDragging.current) {
      meshRef.current.position.set(config.x, config.y, config.z);
      meshRef.current.rotation.set(config.rx, config.ry, config.rz);
      meshRef.current.scale.set(config.scale * 4, config.scale * 3, 1);
    }
  }, [config.x, config.y, config.z, config.rx, config.ry, config.rz, config.scale]);

  return (
    <group {...props} dispose={null}>
      <group position={[0.299, -5.067, -23.901]} rotation={[-1.476, 0, -1.024]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.495, 4.612, -4.267]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.old_pc000_Room_mat_0_0.geometry} material={materials.Room_mat} />
            <mesh geometry={nodes.old_pc000_Room_mat_0_1.geometry} material={materials.Room_mat} />
          </group>
        </group>
      </group>

      {/* TransformControls allows visual dragging, rotating, and scaling directly in the 3D scene */}
      <TransformControls 
        mode={props.transformMode || 'translate'}
        onDraggingChanged={(e) => { 
          isDragging.current = e?.value ?? false; 
          // Commit the final state to React when dragging stops
          if (!isDragging.current && props.onTransformChange && meshRef.current) {
             const pos = meshRef.current.position;
             const rot = meshRef.current.rotation;
             const scale = meshRef.current.scale.x / 4;
             props.onTransformChange({
                x: pos.x, y: pos.y, z: pos.z,
                rx: rot.x, ry: rot.y, rz: rot.z,
                scale: scale
             });
          }
        }}
        onObjectChange={() => {
          // BLAZING FAST PURE DOM UPDATE (Bypasses React entirely to prevent Canvas lag!)
          if (meshRef.current) {
             const pos = meshRef.current.position;
             const rot = meshRef.current.rotation;
             const scale = meshRef.current.scale.x / 4;
             
             const updateEl = (id: string, val: number) => {
               const el = document.getElementById(`calib-${id}`) as HTMLInputElement;
               if (el && document.activeElement !== el) el.value = val.toFixed(2);
             };
             
             updateEl('x', pos.x); updateEl('y', pos.y); updateEl('z', pos.z);
             updateEl('rx', rot.x); updateEl('ry', rot.y); updateEl('rz', rot.z);
             updateEl('scale', scale);
             
             const jsonEl = document.getElementById('calib-json');
             if (jsonEl) jsonEl.textContent = JSON.stringify({
                x: Number(pos.x.toFixed(3)), y: Number(pos.y.toFixed(3)), z: Number(pos.z.toFixed(3)),
                rx: Number(rot.x.toFixed(3)), ry: Number(rot.y.toFixed(3)), rz: Number(rot.z.toFixed(3)),
                scale: Number(scale.toFixed(3))
             });
          }
        }}
      >
        <mesh ref={meshRef}>
          <planeGeometry args={[1, 1]} />
          <meshBasicMaterial color="#00ff00" opacity={0.7} transparent side={THREE.DoubleSide} depthTest={false} />
        </mesh>
      </TransformControls>
    </group>
  )
}

useGLTF.preload('/Sad_Office_Room/Sad_Office_Room.glb')
