/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to include the embedded OS screen on the monitor glass.
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { OSBootSequence } from './hero-section'

type GLTFResult = GLTF & {
  nodes: {
    old_pc000_Room_mat_0_0: THREE.Mesh
    old_pc000_Room_mat_0_1: THREE.Mesh
  }
  materials: {
    Room_mat: THREE.MeshStandardMaterial
  }
  animations: unknown[]
}

export function SadOfficeRoom(props: React.JSX.IntrinsicElements['group'] & { 
  isBootingOS?: boolean;
  onCompleteBoot?: () => void;
}) {
  const { nodes, materials } = useGLTF('/Sad_Office_Room/Sad_Office_Room.glb') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0.299, -5.067, -23.901]} rotation={[-1.476, 0, -1.024]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.495, 4.612, -4.267]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.old_pc000_Room_mat_0_0.geometry} material={materials.Room_mat} />
            <mesh geometry={nodes.old_pc000_Room_mat_0_1.geometry} material={materials.Room_mat} />
          </group>
        </group>
      </group>

      {/* Embedded OS Screen - Hardcoded to the user's calibrated coordinates */}
      <Html 
        transform 
        occlude="blending"
        position={[6.237, 1.437, -31.029]} 
        rotation={[-0.528, -0.897, -0.504]}
        scale={0.286}
        className="w-[800px] h-[600px] bg-black flex items-center justify-center border-4 border-[#0a0a0a]"
        style={{ borderRadius: '32px', overflow: 'hidden' }} // Rounded corners to match CRT bezel
      >
        <div className="w-full h-full relative" style={{ borderRadius: '32px', overflow: 'hidden' }}>
          {/* CRT Scanline Overlay */}
          <div className="absolute inset-0 pointer-events-none z-50 mix-blend-overlay opacity-30" 
            style={{
              backgroundImage: "linear-gradient(transparent 50%, rgba(0, 0, 0, 0.5) 50%)",
              backgroundSize: "100% 4px"
            }}
          />
          {/* CRT Screen Glare */}
          <div className="absolute inset-0 pointer-events-none z-50 mix-blend-screen opacity-10 bg-gradient-to-tr from-transparent via-white to-transparent" />
          
          {props.isBootingOS ? (
            <OSBootSequence onComplete={() => props.onCompleteBoot?.()} />
          ) : (
            <iframe 
              src="/monitor-os/index.html" 
              className="w-full h-full border-0"
              title="Desktop OS"
            ></iframe>
          )}
        </div>
      </Html>
    </group>
  )
}

useGLTF.preload('/Sad_Office_Room/Sad_Office_Room.glb')
